name: todo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
#  sqlite3_flutter_libs: ^0.5.31
  path_provider: ^2.1.5
  provider: ^6.1.4
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  google_fonts: ^6.2.1
  confetti: ^0.8.0
  easy_date_timeline: ^2.0.9
  flutter_bloc: ^9.1.0
  intl: ^0.20.2


dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0

dependency_overrides:
  intl: 0.20.2

flutter:
  uses-material-design: true
